### ISSUE TITLE
make installation with pip possible

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/allowed#11]
Find out how to make a pip package and add `allowed` to the Python Package Index.

**Comment by mwermelinger** [comment]
Tutorial at https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by mwermelinger** [comment]
`allowed` is now on [TestPyPi](https://test.pypi.org/project/allowed/) but not yet working. TestPyPi uses 2FA, so a project can't be published with username/pwd; only with an API token or a trusted publisher like GitHub Actions. The steps were:

1. Tell `poetry` the URL of the repo to publish to: `poetry config repositories.testpypi https://test.pypi.org/legacy/`
1. Log into my TestPyPi account and create an API token `pypi-...`
2. Tell poetry it should publish using that token: `poetry config http-basic.testpypi __token__ pypi-...`
3. Bump up the version number in `pyproject.toml` because the same version can't be published twice. I'm using [developmental versions](https://packaging.python.org/en/latest/specifications/version-specifiers/#developmental-releases).
1. Build and publish to TestPyPi: `poetry publish --build -r testpypi`

To test the installation, I created and activated a new venv with Python 3.10, and ran `pip install -i https://test.pypi.org/simple/ allowed==1.2.0.dev1` but got installation issues. Apparently TestPyPi doesn't include a recent `ipython`, and for some reason installing `pytype` complains that it can't satisfy `setuptools` > 40.8, even though the venv has `setuptools 65.5. I hope it works with the real PyPi. 

Commenting out both dependencies in `pyproject.toml` makes `pip install` work. However, the built wheel only has the `allowed.py` file and not the configuration files. Several things to do:

- [ ] include configuration files in the installation
- [ ] skip installation of pytype on Windows
- [ ] make `allowed` an executable that can be called from command line
- [ ] make `allowed` look into its own folder for the configuration files

**Comment by mwermelinger** [comment]
It seems it's possible to leave the dependencies in `pyproject.toml` and do `pip install --no-deps -i ...`, to avoid trying installing dependencies that may not exist on TestPyPi.

**Comment by densnow** [comment]
Here is some documentation that might also be useful for skipping `pytype` installation on windows: [Using environment markers](https://python-poetry.org/docs/dependency-specification/#using-environment-markers) and [Environment markers](https://peps.python.org/pep-0508/#environment-markers) 

 Something like the following in `pyproject.toml` could work
```toml
[tool.poetry.dependencies]
#...
pytype = { version = "^2023.11.29", markers = "platform_system != 'Windows'" }
```

For making `allowed` an executable see [scripts](https://python-poetry.org/docs/pyproject/#scripts). It looks like an entry point to `allowed` must be defined E.g a `main()` or `run()` function then something like the following could be added to the TOML
```toml
[tool.poetry.scripts]
allowed = 'allowed:Main'
```

**Comment by mwermelinger** [comment]
- I managed to make [paddles](https://github.com/dsa-ou/paddles) pip'able. I think we need a subfolder `allowed/` with the `.py` and `.json` files and an empty `__init__.py`.
- The installation can be done locally, without going through TestPyPi, with`pip path/to/allowed_project`. This allows to check things before putting on TestPyPi and then on PyPi.
- `allowed` works if IPython and `pytype` aren't present, so we could for the moment leave it to the user to install those if they wish. Those dependencies could move to the development group.

**Comment by scmmmh** [comment]
Just a few notes on publishing PyPi packages easily:

* Yes, the "allowed" subfolder is the way to go. You can then load the config files using importlib resources: https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources
* If you move the code in your "if __name__ ==..." into a "__main__.py" in the "allowed" subfolder, then you can run the application using "python -m allowed". Then later, for building a nice CLI interface, I can recommend Typer (https://typer.tiangolo.com/) and that can then be used for working with the tool.poetry.scripts section.
* The best way to publish is from a GitHub action. Then you can tag your release and it gets built and published. See here for an example: https://github.com/uEdition/uEdition/blob/main/.github/workflows/release.yml
* PyPI now has the concept of trusted publishers, which is great for automation from GitHub, because it means you don't have to mess about with setting up the tokens. See https://docs.pypi.org/trusted-publishers/
* Instead of using environment markers, optional extra dependency sets are also supported by Poetry: https://python-poetry.org/docs/pyproject/#extras

I've built and published a number of CLI applications over the years, so if you have any questions, please just tag me in (@scmmmh).

**Comment by mwermelinger** [comment]
To check pip installation change to a folder outside the repo, e.g. your home folder. Then:
- create a virtual env, e.g. `python3.10 -m venv ~/testenv`
- activate it, e.g. `. ~/testenv/bin/activate`
- install `allowed`: `pip install ~/dsa-ou/allowed`
- try it out, e.g. `allowed ~/dsa-ou/allowed/sample.ipynb -c tm112.json` or `python -m allowed ~/dsa-ou/....`
- do `pip install '/Users/.../dsa-ou/allowed[ipython]'` (can't use ~) and check again the sample notebook
- finally do `pip install '/Users/.../dsa-ou/allowed[pytype]'` and check again sample notebook with `-m` option

**Comment by mwermelinger** [comment]
@densnow I've put `allowed` on PyPi. It can be installed in 4 ways:
- `pip install allowed`
- `pip install 'allowed[ipython]'` 
- `pip install 'allowed[pytype]'` 
- `pip install 'allowed[all]'` to install both 

Could you try the latter in a new virtual env on Windows? Let me know if pytype is installed or not. Thanks. If it's all fine, I will update the installation instructions and then merge the branch for this issue into main.

**Comment by densnow** [comment]
@mwermelinger After running the command `pip install 'allowed[all]'` in a brand new venv on Windows 10, `pytype` was **not** installed.

**Comment by densnow** [comment]
@mwermelinger If `allowed` is now on Pypi, it would be nice to have `--version` and `-v` commands to print the version (and quickly check if it is installed). Also I noticed when the usage instructions are printed there is reference to `allowed.py` rather than `allowed` which might not make sense in the new context.

**Comment by mwermelinger** [comment]
Thanks for checking. Good point about the version. But where does the usage refer to `allowed.py`? If I type `allowed -h` I don't see it. But if I type `python -m allowed -h` then the usage mentions `__main__.py`. I'll fix these things before merging.

**Comment by densnow** [comment]
My mistake, I thought the usage message was generated by `allowed` but It seems this message is generated by `argparser` when an unknown argument is given. 

The message was printed when I tried `allowed --version`

**Comment by mwermelinger** [comment]
- [ ] update installation.md
- [ ] see if there's a way for `argparser` to not display `__main__.py`
